server:
  port: 8053
spring:
  application:
    name: rabbitmq-hello
  rabbitmq:
    #不能为localhost,否则报错
    host: 127.0.0.1
    #15672是Web管理界面的端口；5672是MQ访问的端口
    port: 5672
    username: ltt
    password: xns2189543
    #这个虚拟的东西一定要授权
    virtual-host: /xns_test